# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 14b8dbe1c7198db09ef539fc51e5c2ebcea789e67daae9b38ebcb18e013a414dca1dbbe39e9c1b9c27d58f64360d8a05b13929a7772b4e0ff357fe053d650e14

test:
  secret_key_base: 224c9c9cde0dadcbaad3cf2e1c9d629f63c1bbd3bc576bed8c2b42bc5e36252419361b240584f36579947cdea30797fe6cc1007b37269ec133af358d856bd891

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
